from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
branch_whitelist = [
    "main"
]
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[Check current commit message]"
cog verify --file $1

echo "[Conventional commit check]"
cog check

echo "[Format code]"
cargo fmt -v --all --check

echo "[Lints]"
cargo clippy
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []


