name: Verify PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  pull-requests: read

jobs:
  verify-pr-title:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cocogitto
        uses: cocogitto/cocogitto-action@v4
        with:
          command: help
          
      - name: Verify PR title follows conventional commits
        run: |
          cog check "${{ github.event.pull_request.title }}"

